# Robot Physical Constraints
robot:
  max_velocity: 3.0  # m/s
  max_acceleration: 2.5  # m/s^2
  max_angular_velocity: 3.14159  # rad/s (180 deg/s)
  max_angular_acceleration: 6.28  # rad/s^2
  radius: 0.45  # meters (with bumpers)
  track_width: 0.6  # meters
  wheelbase: 0.6  # meters

# Path Planning Parameters
planning:
  algorithm: "hybrid"
  frequency_hz: 20  # Hz
  deviation_threshold: 0.3  # meters
  replanning_enabled: true
  heuristic_weight: 1.0  # A* heuristic weight (1.0 = optimal, >1 = faster but suboptimal)
  max_iterations: 10000
  timeout_ms: 500  # Maximum planning time
  hybrid:
    step_size: 0.25
    grid_resolution: 0.25
    heading_divisions: 64
    min_turning_radius: 0.75
    max_curvature: 0.0
    curvature_samples: "-1.0,-0.5,0.0,0.5,1.0"
    allow_reverse: true
    allow_holonomic: true
    allow_in_place_rotation: true
    holonomic_step: 0.25
    reverse_penalty: 2.0
    turn_penalty: 0.35
    holonomic_penalty: 1.1
    rotation_penalty: 0.5
    rotation_weight: 0.25
    goal_position_tolerance: 0.3
    goal_heading_tolerance_deg: 12.0
    rotation_step_deg: 10.0
    collision_samples: 12
  grid_collision_margin: 0.15

# Field Configuration
field:
  config_format: "navgrid"  # Options: "navgrid" or "field_config"
  config_path: "config/navgrid.json"  # Path to field configuration

# Path Optimization
optimization:
  smoothing_enabled: true
  bezier_points_per_segment: 10
  max_curvature: 2.0  # rad/m
  simplification_enabled: true
  shortcut_enabled: true
  cost_weights:
    distance: 1.0
    curvature: 0.3
    obstacle_proximity: 0.5
    time: 0.8

# Velocity Profiling
velocity_profile:
  time_step: 0.02  # seconds (50 Hz)
  acceleration_limit_factor: 0.9  # Use 90% of max acceleration for safety
  deceleration_distance_buffer: 0.5  # meters

# Network Communication
network:
  robot_pose_topic: "robot_pose"
  target_pose_topic: "target_pose"
  trajectory_topic: "trajectory"
  vision_table: "vision"
  planner_table: "pathplanner"
  update_rate_hz: 50  # Hz

# Vision Integration
vision:
  enabled: true
  latency_compensation: true
  max_latency_ms: 100
  use_field_relative: true  # Use field-relative from roboRIO
  fallback_to_robot_relative: true  # Fallback if field-relative unavailable
  object_types:
    - "algae"
  
  # Algae-specific settings
  algae:
    radius: 0.1905  # 7.5 inches in meters
    min_confidence: 0.45
    tracking_enabled: true
    max_age_ms: 2000

# Dynamic Obstacles
obstacles:
  prediction_time: 0.5  # Algae are stationary, shorter prediction
  expiry_time_ms: 2000
  min_confidence: 0.45
  inflation_radius: 0.3  # Safety margin around algae (meters)
  tracking_enabled: true

# Logging and Debugging
logging:
  enabled: true
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_planning_time: true
  log_replanning_triggers: true
  log_obstacle_updates: false

# Performance Tuning
performance:
  multi_threading: true
  cache_visibility_graph: true
  lazy_evaluation: true
  early_termination: true

# NavGrid Specific Settings
navgrid:
  snap_to_grid: false  # Whether to snap waypoints to grid cells
  diagonal_movement: true  # Allow diagonal movement in grid
  corner_cutting: false  # Prevent cutting corners around obstacles

# Predefined objective poses for processor and barge cycles
objectives:
  processor:
    default:
      - name: "ProcessorFront"
        position: { x: 2.75, y: 5.90, z: 0.0 }
        rotation: { roll: 0.0, pitch: 0.0, yaw: 1.57 }
    amp-side:
      - name: "ProcessorAmpSide"
        position: { x: 2.40, y: 6.40, z: 0.0 }
        rotation: { roll: 0.0, pitch: 0.0, yaw: 1.57 }
  barge:
    default:
      - name: "BargeCenter"
        position: { x: 10.80, y: 1.70, z: 0.0 }
        rotation: { roll: 0.0, pitch: 0.0, yaw: 3.14 }
    source-side:
      - name: "BargeSourceSide"
        position: { x: 10.30, y: 2.30, z: 0.0 }
        rotation: { roll: 0.0, pitch: 0.0, yaw: 2.60 }

# Autonomous routine definitions for the planner
autonomous:
  routines:
    - name: "two-algae-barge"
      start:
        name: "SourceStart"
        position: { x: 1.50, y: 1.20, z: 0.0 }
        rotation: { roll: 0.0, pitch: 0.0, yaw: 0.0 }
      objectives:
        - type: ALGAE
          count: 2
        - type: BARGE
          label: "default"
          count: 1
    - name: "three-algae"
      start:
        name: "ReefStart"
        position: { x: 1.80, y: 3.40, z: 0.0 }
        rotation: { roll: 0.0, pitch: 0.0, yaw: 0.0 }
      objectives:
        - type: ALGAE
          count: 3